module.exports = {
	DEPOSIT_STATE: {
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		PENDING: 'PENDING',
		EXPIRED: 'EXPIRED',
		CANCELED: 'CANCELED',
	},
	ISEC_STATE: {
		REQUESTING: 'REQUESTING',
		PENDING: 'PENDING',
		DONATED: 'DONATE',
		USED: 'USED',
		DEPOSIT: 'DEPOSIT',
		LOCKED: 'LOCKED',
		CANCELED: 'CANCELED',
		FAILED: 'FAILED',
		EXPIRED: 'EXPIRED',
	},
	ISEC_BULKID_STATE: {
		NEW: 'NEW',
		CREATING: 'CREATING',
		CREATED: 'CREATED',
		FAILED: 'FAILED',
	},
	ISEC_ORDER_STATE: {
		NEW: 'NEW',
		PENDING: 'PENDING',
		PROCESSING: 'PROCESSING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		CANCELED: 'CANCELED',
	},
	ISEC_SOURCE: {
		SAVED: 'SAVED',
		TRANSFERRED: 'TRANSFERRED',
		CREATED: 'CREATED',
	},
	ISEC_FORMAT: {
		PREFIX_LENGTH: 8,
		ISEC_LENGTH: 8,
		HINT_LENGTH: 4,
	},
	ORDER_STATE: {
		NEW: 'NEW',
		PENDING: 'PENDING',
		PROCESSING: 'PROCESSING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		CANCELED: 'CANCELED',
	},
	DEPOSIT_TYPE: {
		BANKING: 'BANKING',
		CREDIT_CARD: 'CREDIT_CARD',
		ISEC: 'ISEC',
		RECEIVE_TRANSFER: 'RECEIVE_TRANSFER',
		MANUAL: 'MANUAL',
		MANUAL_DEPOSIT: 'MANUAL_DEPOSIT',
		SYSTEM_DEPOSIT: 'SYSTEM_DEPOSIT',
	},
	WITHDRAW_REQUEST_STATE: {
		PENDING: 'PENDING',
		APPROVED: 'APPROVED',
		APPROVING: 'APPROVING',
		REJECTED: 'REJECTED',
		CANCELED: 'CANCELED',
		BANK_FAILED: 'BANK_FAILED',
		FAILED: 'FAILED',
	},
	WITHDRAW_TYPE: {
		WITHDRAW: 'WITHDRAW',
		MANUAL_WITHDRAW: 'MANUAL_WITHDRAW',
		BANKING_WITHDRAW: 'BANKING_WITHDRAW',
		SYSTEM_WITHDRAW: 'SYSTEM_WITHDRAW',
	},
	CASHBACK_STATE: {
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	BANK_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		CANCELED: 'CANCELED',
		APPROVED: 'APPROVED',
		REJECTED: 'REJECTED',
	},
	USER_TRANSACTION_MONEY_LIMIT: {
		DAY_LIMIT: 100000000,
		TRANSACTION_LIMIT: 'FAILED',
		NITGH_LIMIT: 5000000,
		NEW_ACOUNT_LIMIT: 5000000,
		DAY_DEPOSIT_LOW_LIMIT: 20000000,
		DAY_DEPOSIT_MEDIUM_LIMIT: 50000000,
		DAY_DEPOSIT_HIGH_LIMIT: 100000000,
		DAY_DEPOSIT_LOW_COUNT_LIMIT: 7,
		DAY_DEPOSIT_MEDIUM_COUNT_LIMIT: 10,
		DAY_DEPOSIT_HIGH_COUNT_LIMIT: 20,
		DAY_WITHDRAW_LOW_LIMIT: 20000000,
		DAY_WITHDRAW_MEDIUM_LIMIT: 50000000,
		DAY_WITHDRAW_HIGH_LIMIT: 100000000,
		DAY_WITHDRAW_LOW_COUNT_LIMIT: 7,
		DAY_WITHDRAW_MEDIUM_COUNT_LIMIT: 10,
		DAY_WITHDRAW_HIGH_COUNT_LIMIT: 20,
		IP_DURATION_LIMIT: 600,
		LIQUIDIDY_SERVICE: ['ISEC', 'CARD'],
		DAY_LIQUIDIDY_LIMIT: 5000000,
	},
	NOTIFICATION_TYPE: {
		USER: 'USER',
		PROMOTION: 'PROMOTION',
		SYSTEM: 'SYSTEM',
	},
	TOP_PAYME_USER_TYPE: {
		DEPOSIT: 'DEPOSIT',
		WITHDRAW: 'WITHDRAW',
		ISEC: 'ISEC',
		BUILKID: 'BUILKID',
		TOPUP: 'TOPUP',
		CARD: 'CARD',
	},
	WITHDRAW_SYSTEM_STATE: {
		SUCCEEDED: 'SUCCEEDED',
		PENDING: 'PENDING',
		FAILED: 'FAILED',
	},
	DEPOSIT_SYSTEM_STATE: {
		SUCCEEDED: 'SUCCEEDED',
		PENDING: 'PENDING',
		FAILED: 'FAILED',
	},
	BILL_SERVICE: {
		POWE: 'POWE',
		ADSL: 'ADSL',
		WATE: 'WATE',
		TIVI: 'TIVI',
		PPMB: 'PPMB',
		ATIC: 'ATIC',
		FTEL: 'FTEL',
		LLNE: 'LLNE',
		PSTN: 'PSTN',
		TAICHINH: 'TAICHINH',
		BAOHIEM: 'BAOHIEM',
		HOCPHI: 'HOCPHI',
		OTHER: 'OTHER',
	},
	DEFAULT_BANK_FEE: {
		MIN_FEE: 3300,
		PVCBANK_WITHDRAW: 0.3,
		MANUAL_WITHDRAW: 0.5,
		DEPOSIT: 0,
	},
	BANK_TRANSACTION_LIMIT: {
		MIN: 1000,
		MAX: 10000000,
	},
	USER_LIMIT_RULE: {
		LEGIT: 0,
		OVER_DAY_QUOTA: 1,
		OVER_MONTH_QUOTA: 2,
	},
	SOCIAL_LINK_DEFAULT_FEE: {
		PAYME: 0,
		NAPAS: 0,
		MOMO: 0,
		ZALO_PAY: 0,
	},
	HISTORY_STATE: {
		PENDING: 'PENDING',
		PROCESSING: 'PROCESSING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		EXPIRED: 'EXPIRED',
		CANCELED: 'CANCELED', // refund
		null: null,
	},
	TRANSFER_MONEY_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	WITHDRAW_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	TRANSFER_METHOD_PAYME_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	TRANSFER_METHOD_LINKED_PVCBANK_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	SETTING_TYPE: {
		STRING: 'STRING',
		NUMBER: 'NUMBER',
		JSON: 'JSON',
		null: null,
	},
	PREFIX_CONFIG_TYPE: {
		ALPHABET: 'ALPHABET',
		NUMBER: 'NUMBER',
		ALPHABET_AND_NUMBER: 'ALPHABET_AND_NUMBER',
	},
	UUID_STATE: {
		NEW: 'NEW',
		USED: 'USED',
	},
	BILL_TRANSACTION_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	BILL_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		WAITING: 'WAITING', // Trạng thái waiting chỉ dành cho SSCC Service
		CANCELED: 'CANCELED', // huy => refund
	},
	BILL_ITEM_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	SOCIAL_LINK_PASSWORD_SALT: '12!36@&E@)!475vqL86',
	SOCIAL_LINK_TYPE: {
		SEND_MONEY: 'SEND_MONEY',
		REQUEST_MONEY: 'REQUEST_MONEY',
		DONATE_MONEY: 'DONATE_MONEY',
	},
	SOCIAL_LINK_STATE: {
		USED: 'USED',
		FAILED: 'FAILED',
		EXPIRED: 'EXPIRED',
		CANCELED: 'CANCELED',
		RECEIVED: 'RECEIVED',
		SUCCEEDED: 'SUCCEEDED',
		PENDING: 'PENDING',
	},
	SOCIAL_TRANSFER_MONEY_SOURCE: {
		EWALLET_PAYME: 'EWALLET_PAYME',
		EWALLET_MOMO: 'EWALLET_MOMO',
		BANK_NAPAS: 'BANK_NAPAS',
		BANK_LINKED: 'BANK_LINKED',
		VISA: 'VISA',
		ISEC: 'ISEC',
	},
	SOCIAL_TRANSFER_MONEY_STATE: {
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		PENDING: 'PENDING',
		EXPIRED: 'EXPIRED',
		CANCELED: 'CANCELED',
	},
	SOCIAL_CHANNEL: {
		MESSENGER: 'MESSENGER',
		ZALO: 'ZALO',
		VIBER: 'VIBER',
		SKYPE: 'SKYPE',
		LINE: 'LINE',
		TELEGRAM: 'TELEGRAM',
		WHATSAPP: 'WHATSAPP',
		WECHAT: 'WECHAT',
		SMS: 'SMS',
		EMAIL: 'EMAIL',
		PAYME: 'PAYME',
		NULL: null,
	},
	GATEWAY_PAYMENT_STATE: {
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		PENDING: 'PENDING',
		CANCELED: 'CANCELED',
	},
	PAYMENT_SERVICE: {
		ISEC: 'ISEC',
		SOCIAL_DONATE_MONEY_LINK: 'SOCIAL_DONATE_MONEY_LINK',
		SOCIAL_SEND_MONEY_LINK: 'SOCIAL_SEND_MONEY_LINK',
		SOCIAL_REQUEST_MONEY_LINK: 'SOCIAL_REQUEST_MONEY_LINK',
		MOBILE_CARD: 'MOBILE_CARD',
		MOBILE_TOPUP: 'MOBILE_TOPUP',
		BILL: 'BILL',
		SSCC: 'SSCC', // chi tach phuong thuc thanh toan, service van la BILL
	},
	SERVICES: {
		LOGIN_TRUST_DEVICE: 'LOGIN_TRUST_DEVICE',
		KYC_APPROVED: 'KYC_APPROVED',
		KYC_REJECTED: 'KYC_REJECTED',
		BILL: 'BILL', // thanh toan hoa don
		ISEC: 'ISEC',
		SALARY: 'SALARY',
		CASHBACK: 'CASHBACK', // tien hoa hong
		ISEC_BULK: 'ISEC_BULK', // hoa don iSec
		ISEC_REDEEM: 'ISEC_REDEEM', // nap isec vao vi
		ISEC_SCRATCH: 'ISEC_SCRATCH', // gach iSec (gate)
		ISEC_SEND: 'ISEC_SEND', // gửi iSec
		ISEC_SAVE: 'ISEC_SAVE', // lưu iSec
		ISEC_RECEIVED: 'ISEC_RECEIVED', // nhận isec từ ng khác transfer
		ISEC_DONATED: 'ISEC_DONATED', // isec được lưu bởi người khác
		CANCEL_ISEC: 'CANCEL_ISEC',
		SOCIAL_LINK: 'SOCIAL_LINK', // service code gửi qua payment cho các loại link social
		SOCIAL_PAYMENT: 'SOCIAL_PAYMENT', // service cho social payment mới

		SOCIAL_DONATE_MONEY_LINK: 'SOCIAL_DONATE_MONEY_LINK', // tạo link donate
		SOCIAL_DONATE_MONEY: 'SOCIAL_DONATE_MONEY', // thanh toán link donate

		SOCIAL_REQUEST_MONEY_LINK: 'SOCIAL_REQUEST_MONEY_LINK', // tạo link yc thanh toán
		SOCIAL_SEND_MONEY: 'SOCIAL_SEND_MONEY', // thanh toán link yc thanh toán

		SOCIAL_SEND_MONEY_LINK: 'SOCIAL_SEND_MONEY_LINK', // tạo link thanh toán
		SOCIAL_PAYME_RECEIVE_MONEY: 'SOCIAL_PAYME_RECEIVE_MONEY', // nhận tiền link thanh toán bằng payme,
		SOCIAL_NAPAS_RECEIVE_MONEY: 'SOCIAL_NAPAS_RECEIVE_MONEY', // nhận tiền link thanh toán bằng Napas,
		SOCIAL_SEND_MONEY_LINK_RECIPIANT: 'SOCIAL_SEND_MONEY_LINK_RECIPIANT', // service notify cho nguoi nhận da nhan link
		REFUND_MONEY: 'REFUND_MONEY', // hoàn tiền giao dịch
		ADD_MONEY: 'ADD_MONEY', // nap tien tu he thong
		MINUS_MONEY: 'MINUS_MONEY', // tru tien tu he thong
		WITHDRAW_BANK_MANUAL: 'WITHDRAW_BANK_MANUAL', // rut tien thu cong
		DEPOSIT_BANK_MANUAL: 'DEPOSIT_BANK_MANUAL', // nap tien thu cong
		LINKED: 'LINKED', // Lien ket the
		DEPOSIT_PVCBANK: 'DEPOSIT_PVCBANK', // v1
		WITHDRAW_PVCBANK: 'WITHDRAW_PVCBANK', // v1
		WITHDRAW_PAYME: 'WITHDRAW_PAYME', // rut tien tu vi payme
		MOBILE_CARD: 'MOBILE_CARD', // mua the cao
		MOBILE_TOPUP: 'MOBILE_TOPUP', // nap tien dien thoai
		DEPOSIT: 'DEPOSIT', // nap tien vao vi
		PAYMENT: 'PAYMENT', // thanh toan giao dich

		WITHDRAW_BANK_GATEWAY: 'WITHDRAW_BANK_GATEWAY', // rút tiên từ payme ve napas ko liên kết
		WITHDRAW_BANK_LINKED_PVCBANK: 'WITHDRAW_BANK_LINKED_PVCBANK', // rút tiền từ payme vè pvcb
		WITHDRAW_BANK_LINKED_GATEWAY: 'WITHDRAW_BANK_LINKED_GATEWAY', // rút tiên từ payme vè napas  liên kết,
		WITHDRAW_BANK_LINKED_OCBBANK: 'WITHDRAW_BANK_LINKED_OCBBANK', // rut tien tu payme ve ocb

		PAYME_SEND_MONEY: 'PAYME_SEND_MONEY',
		PAYME_RECEIVE_MONEY: 'PAYME_RECEIVE_MONEY',
		TRANSFER_PAYME: 'TRANSFER_PAYME',

		GATEWAY_PAYMENT: 'GATEWAY_PAYMENT',

		SOCIAL_PAYMENT_REQUEST_MONEY_LINK: 'SOCIAL_PAYMENT_REQUEST_MONEY_LINK',
		SOCIAL_PAYMENT_RECEIVE_REQUEST_MONEY_LINK: 'SOCIAL_PAYMENT_RECEIVE_REQUEST_MONEY_LINK',
		SOCIAL_PAYMENT_SEND_MONEY_LINK: 'SOCIAL_PAYMENT_SEND_MONEY_LINK',
		SOCIAL_PAYMENT_DONATE_MONEY_LINK: 'SOCIAL_PAYMENT_DONATE_MONEY_LINK',
		SOCIAL_PAYMENT_PAYME_RECEIVE_MONEY: 'SOCIAL_PAYMENT_PAYME_RECEIVE_MONEY',
		SOCIAL_PAYMENT_NAPAS_RECEIVE_MONEY: 'SOCIAL_PAYMENT_NAPAS_RECEIVE_MONEY',
		SOCIAL_PAYMENT_SEND_MONEY: 'SOCIAL_PAYMENT_SEND_MONEY',
		SOCIAL_PAYMENT_DONATE_MONEY: 'SOCIAL_PAYMENT_DONATE_MONEY',

		ADVANCE_MONEY: 'ADVANCE_MONEY', // ƯNG TIỀN
		CREDIT_STATEMENT: 'CREDIT_STATEMENT', // THANH TOÁN NỢ
		CREDIT_SETTLEMENT: 'CREDIT_SETTLEMENT', // TẤT TOÁN NỢ
		PAYME_CREDIT: 'PAYME_CREDIT', // THANH TOÁN DỊCH VỤ
	},
	TAGS: {
		BILL: 'BILL',
		BILL_EXTEND: 'BILL_',
		ISEC: 'ISEC',
		ISEC_CREATE: 'ISEC_CREATE',
		ISEC_BULK: 'ISEC_BULK',
		ISEC_SCRATCH: 'ISEC_SCRATCH',
		ISEC_SEND: 'ISEC_SEND',
		ISEC_SAVE: 'ISEC_SAVE',
		CASHBACK: 'CASHBACK',
		CASHBACK_ISEC: 'CASHBACK_ISEC',
		CASHBACK_ISEC_BULK: 'CASHBACK_ISEC_BULK',
		RECEIVE_MONEY_ISEC: 'RECEIVE_MONEY_ISEC',
		RECEIVE_MONEY: 'RECEIVE_MONEY',
		SEND_MONEY: 'SEND_MONEY',
		DONATE_LINK: 'DONATE_LINK',
		REFUND_MONEY: 'REFUND_MONEY',
		SOCIAL_LINK_REQUEST_MONEY: 'SOCIAL_LINK_REQUEST_MONEY',
		SOCIAL: 'SOCIAL',
		SOCIAL_LINK: 'SOCIAL_LINK',
		INTERNAL: 'INTERNAL',
		INTERNAL_MONEY: 'INTERNAL_MONEY',
		ADD_MONEY: 'ADD_MONEY',
		MINUS_MONEY: 'MINUS_MONEY',
		DEPOSIT: 'DEPOSIT',
		DEPOSIT_BANK: 'DEPOSIT_BANK',
		DEPOSIT_BANK_MANUAL: 'DEPOSIT_BANK_MANUAL',
		SALARY: 'SALARY',
		PAYME_SALARY: 'PAYME_SALARY',
		GATE_SALARY: 'GATE_SALARY',
		DEPOSIT_BANK_MANUAL_EXXTEND: 'DEPOSIT_BANK_MANUAL_',
		WITHDRAW: 'WITHDRAW',
		WITHDRAW_BANK: 'WITHDRAW_BANK',
		WITHDRAW_BANK_OCBBANK: 'WITHDRAW_BANK_OCBBANK',
		WITHDRAW_BANK_MANUAL: 'WITHDRAW_BANK_MANUAL',
		WITHDRAW_BANK_MANUAL_EXXTEND: 'WITHDRAW_BANK_MANUAL_',
		LINKED: 'LINKED',
		LINKED_PVCBANK: 'LINKED_PVCBANK',
		LINKED_VIETIN: 'LINKED_VIETIN',
		LINKED_NAPAS: 'LINKED_NAPAS',
		DEPOSIT_BANK_PVCBANK: 'DEPOSIT_BANK_PVCBANK',
		WITHDRAW_BANK_PVCBANK: 'WITHDRAW_BANK_PVCBANK',
		WITHDRAW_BANK_NAPAS: 'WITHDRAW_BANK_NAPAS',
		MOBILE_CARD: 'MOBILE_CARD',
		MOBILE_TOPUP: 'MOBILE_TOPUP',
		CASHBACK_BUYCARD: 'CASHBACK_BUYCARD',
		CASHBACK_TOPUP: 'CASHBACK_TOPUP',
		BONUS: 'BONUS',
		DISCOUNT: 'DISCOUNT',
		DISCOUNT_MOBILE_CARD: 'DISCOUNT_MOBILE_CARD_',
		MOBILE_CARD_EXTEND: 'MOBILE_CARD_',
		DISCOUNT_MOBLE_TOPUP: 'DISCOUNT_MOBLE_TOPUP',
		MOBILE_TOPUP_EXTEND: 'MOBILE_TOPUP_',
		DEPOSIT_LINKED: 'DEPOSIT_LINKED',
		WITHDRAW_LINKED: 'WITHDRAW_LINKED',
		PAYMENT: 'PAYMENT',
		PAYMENT_BANK: 'PAYMENT_BANK',
		PAYMENT_BANK_LINKED: 'PAYMENT_BANK_LINKED',
		PAYMENT_BANK_LINKED_PVCOMBANK: 'PAYMENT_BANK_LINKED_PVCOMBANK',
		TRANSFER_PAYME: 'TRANSFER_PAYME',
		GATEWAY_PAYMENT: 'GATEWAY_PAYMENT',
		PAYMENT_BANK_LINKED_OCBBANK: 'PAYMENT_BANK_LINKED_OCBBANK',
		LINKED_OPBBANK: 'LINKED_OPBBANK',
		SOCIAL_PAYMENT: 'SOCIAL_PAYMENT',
		SOCIAL_PAYMENT_LINK: 'SOCIAL_PAYMENT_LINK',
		LINKED_OCBBANK: 'LINKED_OCBBANK',
		LINKED_BIDVBANK: 'LINKED_BIDVBANK',
	},
	TRANSFER_PAYME_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		WAITING: 'WAITING',
		FAILED: 'FAILED',
		CANCELED: 'CANCELED',
	},
	CARD_TRANSACTION_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		WAITING: 'WAITING',
		PROCESSING: 'PROCESSING', // tach khac pending để chạy worker OpenApi
		FAILED: 'FAILED',
		CANCELED: 'CANCELED',
	},
	CARD_ITEM_STATE: {
		PENDING: 'PENDING',
		USED: 'USED',
		REMOVED: 'REMOVED',
	},
	CARD_SUPPLIER: {
		GATE: 'GATE',
		MOBI: 'MOBI',
		VINA: 'VINA',
		VIETTEL: 'VIETTEL',
		GARENA: 'GARENA',
		ZING: 'ZING',
		BEELINE: 'BEELINE',
		KASPERSKY: 'KASPERSKY',
		VCOIN: 'VCOIN',
		VN_MOBI: 'VN_MOBI',
		ECASH: 'ECASH',
	},
	TOPUP_TYPE: {
		PREPAID: 'PREPAID', // thuê bao di động trả trước
		POSTPAID: 'POSTPAID', // thuê bao di động trả sau
	},
	LINKED_TYPE: {
		ATM: 'ATM',
		BANKING: 'BANKING',
		CREDIT_CARD: 'CREDIT_CARD',
		BANKING_OCB: 'BANKING_OCB',
		BANKING_VIETIN: 'BANKING_VIETIN',
	},
	LINKED_STATE: {
		NEW: 'NEW',
		LINKED: 'LINKED',
		LOCKED: 'LOCKED',
		UNLINK: 'UNLINK',
		FAILED: 'FAILED',
	},
	BANK_TYPE: {
		DEPOSIT: 'DEPOSIT',
		WITHDRAW: 'WITHDRAW',
	},
	TRANSFER_TOKEN_SECRET_KEY: 'TRANSFER_8543w%!&$(()@E(#_',
	PAYMENT_TOKEN_SECRET_KEY: 'PAYMENT_8543w%!&$(()@E(#_',
	WITHDRAW_METHOD: {
		PAYME: 'PAYME',
		SOCIAL_SEND_MONEY: 'SOCIAL_SEND_MONEY',
		SOCIAL_RECEIVE_MONEY: 'SOCIAL_RECEIVE_MONEY',
		SOCIAL_DONATE_MONEY: 'SOCIAL_DONATE_MONEY',
		LINKED_BANK_PVCBANK: 'LINKED_BANK_PVCBANK',
		LINKED_BANK_GATEWAY: 'LINKED_BANK_GATEWAY',
		NAPAS_BANK: 'NAPAS_BANK',
		ISEC: 'ISEC',
		SOCIAL_PAYMENT_SEND_MONEY_LINK: 'SOCIAL_PAYMENT_SEND_MONEY_LINK',
		SOCIAL_PAYMENT_RECEIVE_MONEY_LINK: 'SOCIAL_PAYMENT_RECEIVE_MONEY_LINK',
		SOCIAL_PAYMENT_DONATE_MONEY_LINK: 'SOCIAL_PAYMENT_DONATE_MONEY_LINK',
		LINKED_BANK_OCBBANK: 'LINKED_BANK_OCBBANK',
	},
	WITHDRAW_METHOD_GROUP: {
		PAYME: 'PAYME',
		EWALLET: 'EWALLET',
		LINKED_BANK: 'LINKED_BANK',
		GATEWAY: 'GATEWAY',
		LINKED_GATEWAY: 'LINKED_GATEWAY',
		ISEC: 'ISEC',
		OTHER: 'OTHER',
		LINKED_BANK_OCBBANK: 'LINKED_BANK_OCBBANK',
		LINKED_CREDIT: 'LINKED_CREDIT',
	},
	CANCEL_METHOD: {
		PAYME: 'PAYME',
		BANK_NAPAS: 'BANK_NAPAS',
		BANK_LINKED_NAPAS: 'BANK_LINKED_NAPAS',
	},
	TRANSFER_METHOD_ISEC_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	TRANSFER_METHOD_SOCIAL_DONATE_MONEY_LINK_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	TRANSFER_METHOD_SOCIAL_SEND_MONEY_LINK_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	TRANSFER_METHOD_SOCIAL_REQUEST_MONEY_LINK_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	TRANSFER_METHOD_NAPAS_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	TRANSFER_METHOD_OCB_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	PAYMENT_METHOD: {
		PAYME: 'PAYME',
		LINKED_BANK_PVCBANK: 'LINKED_BANK_PVCBANK',
	},
	PAYMENT_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		CANCELED: 'CANCELED',
	},
	REFUND_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	PAYMENT_METHOD_PAYME_STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
	},
	PAYMENT_TYPE: {
		SERVICES: 'SERVICES',
		DEPOSIT: 'DEPOSIT',
	},
	PAYMENT_METHOD_GROUP: {
		PAYME: 'PAYME',
		EWALLET: 'EWALLET',
		LINKED_BANK: 'LINKED_BANK',
		LINKED_CREDIT: 'LINKED_CREDIT',
		GATEWAY: 'GATEWAY',
		LINKED_GATEWAY: 'LINKED_GATEWAY',
		LINKED_BANK_OCBBANK: 'LINKED_BANK_OCBBANK',
		ISEC: 'ISEC',
		DEPOSIT_BANK_MANUAL: 'DEPOSIT_BANK_MANUAL',
		SSCC: 'SSCC',
		VNPAY: 'VNPAY',
		PAYME_CREDIT: 'PAYME_CREDIT',
		OTHER: 'OTHER',
	},
	TRANSFER_GATEWAY_METHOD_TYPE: {
		BANK_ACCOUNT: 'BANK_ACCOUNT',
		BANK_ACCOUNT_OCB: 'BANK_ACCOUNT_OCB',
		ATM_CARD: 'ATM_CARD',
		null: null,
	},
	TRANSACTION_TYPE: {
		DEPOSIT: 'DEPOSIT', // nạp
		WITHDRAW: 'WITHDRAW', // rút
		TRANSFER: 'TRANSFER', // chuyển
		PAYMENT: 'PAYMENT', // thanh toán
		BILL: 'BILL', // hoá đơn
		ISEC: 'ISEC', // ISEC
		TOPUP: 'TOPUP', // Nạp card
	},
	TRANSACTION_METHOD_TYPE: {
		BANK_ACCOUNT: 'BANK_ACCOUNT',
		ATM_CARD: 'ATM_CARD',
		BANKING: 'BANKING',
		PAYME: 'PAYME',
		ISEC: 'ISEC',
		TOPUP: 'TOPUP',
		null: null,
	},
	FEED_POLICY: {
		PUBLIC: 'PUBLIC',
		PRIVATE: 'PRIVATE',
		FRIEND: 'FRIEND',
	},
	FEED_REACTION_TYPE: {
		LIKE: 'LIKE',
	},
	FEED_CONTENT_TYPE: {
		TEXT: 'TEXT',
		IMAGE: 'IMAGE',
		GIFT: 'GIFT',
	},
	FEED_ACTION_TYPE: {
		SEND_LINK: 'SEND_LINK',
		RECEIVE_LINK: 'RECEIVE_LINK',
	},
	SOCIAL_PAYMENT_CONSTANT: {
		FEED_TITLE_ACTION: {
			SEND_MONEY: 'Chuyển tiền',
			REQUEST_MONEY: 'Yêu cầu chuyển tiền',
			RECEIVE_MONEY: 'Nhận tiền',
		},
	},
	ALIAS_STATE: {
		NEW: 'NEW',
		APPROVED: 'APPROVED',
		REJECTED: 'REJECTED',
	},
	ADVERT_TYPE: {
		EMAIL: 'EMAIL',
		FLASH_SCREEN: 'FLASH_SCREEN',
		ADS_BANNER: 'ADS_BANNER',
		PUSH_NOTIFICATION: 'PUSH_NOTIFICATION',
		PUSH_INAPP: 'PUSH_INAPP',
		BROADCAST_MESSAGE_INAPP: 'BROADCAST_MESSAGE_INAPP',
		SCRIPT: 'SCRIPT', // theo kich bản
	},

	ADVERT_AUDIENCE: {
		ALL: 'ALL', // tất cả kh trong payme
		KYC_APPROVED: 'KYC_APPROVED',
		PERSONAL: 'PERSONAL',
		ENTERPRISE: 'ENTERPRISE',
		LIST_CUSTOMER: 'LIST_CUSTOMER',
	},

	ADVERT_POSITION: {
		HOME_SCREEN: 'HOME_SCREEN',
		OTHER: 'OTHER',
	},

	WORD_FILTER_TYPE: {
		COMMENT: 'COMMENT',
		ALIAS: 'ALIAS',
		TRANSACTION: 'TRANSACTION',
		RESPONSE_VI: 'RESPONSE_VI',
		RESPONSE_ENG: 'RESPONSE_ENG',
	},
};
