module.exports = {
	STATE: {
		ACTIVE: 'ACTIVE',
		DEACTIVE: 'DEACTIVE',
		EXPIRED: 'EXPIRED',
		REQUIRE_PERMISSION: 'REQUIRE_PERMISSION',
	},
	SCOPE: {
		BASIC: 'BASIC',
		KYC: 'KYC',
		BALANCE: 'BALANCE',
		PAY: 'PAY',
	},
};
