module.exports = {
	STATE: {
		PENDING: 'PENDING',
		SUCCEEDED: 'SUCCEEDED',
		FAILED: 'FAILED',
		REJECTED: 'REJECTED',
	},
	SERVICE_TYPE: {
		MINI_PROGRAM_ORDER_PAYMENT: 'MINI_PROGRAM_ORDER_PAYMENT',
	},
};
